### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [bitbandi/go-livecoin#1]
Hello, found a few issues with your code. Is this still being developed or have you moved onto something else.

Either way, I fixed it, happy to chat with you sometime about it if you want.

**Comment by bitbandi** [comment]
Feel free to fork the repo, commit your fix, and make a pull request

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
Ah, its no problem. I ended up just removing all the http and mux parts. Were you actually able to get it running on localhost in browser? I kept getting 404 using xampp, tried a number of configurations.

**Comment by bitbandi** [comment]
heh? it's a golang client library. no need to run in browser

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
lol you're right. well i got it to print out tickers in console, unable to get specific orderbook info though. ive been testing multiple repos out for livecoin the past few days. Im just trying to basically make something that can place trades based on orderbook conditions. I've tried some php libraries, python, your go library, someone elses go library. Not having any luck. Thanks for your responses so far btw, if you are ever bored and want to help out a lemming like me, id be happy to compensate you with litecoin or eth. Im basically just doing this all on my own would be great to have someone who knows something to ask a thing or two at most.
