### ISSUE TITLE
Can I do a pull request?

### ISSUE THREAD

**Issue by Tomiyou** [bitbandi/go-livecoin#2]
I added some new features to you api and also replaced float64 with https://github.com/shopspring/decimal that is used by other popular go apis for various exchanges. Would you be ok with these changes to be implemented into your repo?

**Comment by bitbandi** [comment]
show me the changes

**Comment by Tomiyou** [comment]
Sorry for the late response.

I forked your repo and ported all my changes into it. Take a look: https://github.com/Tomiyou/go-livecoin-1
